#:schema https://mise.jdx.dev/schema/mise.json

[tools]
node = "22"

[tasks.lint]
depends = ["lint:check:*"]

[tasks."lint:fix"]
depends = ["lint:fix:*"]

[tasks."lint:check:prettier"]
description = "Run prettier validation"
dir = "docs"
run = "npx prettier --ignore-unknown --check ."

[tasks."lint:fix:prettier"]
description = "Run prettier validation"
dir = "docs"
run = "npx prettier --write ."

[tasks."docs:build"]
description = "Build the documentation site"
dir = "docs"
depends = ["install:docs"]
run = "npm run docs:build"

[tasks."docs:dev"]
description = "Run the documentation dev server"
dir = "docs"
depends = ["install:docs"]
run = "npm run docs:dev"

[tasks."docs:preview"]
description = "Run the documentation preview server"
dir = "docs"
depends = ["install:docs"]
run = "npm run docs:preview"

[tasks.install]
alias = ['i']
depends = ["install:*"]

[tasks."install:docs"]
description = "Install the dependencies for `docs/`"
dir = "docs"
sources = ["package.json"]
outputs = ["package-lock.json"]
run = "npm install"
